// Auto-generated by: npx supabase gen types typescript --local > src/types/database.ts
// DO NOT EDIT MANUALLY — regenerate after any schema change

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole = "student" | "professor" | "admin";
export type CourseStatus = "draft" | "pending" | "approved" | "rejected" | "suspended";
export type CourseLanguage = "python" | "javascript" | "c" | "java" | "html_css" | "sql";
export type CourseLevel = "beginner" | "intermediate";
export type PurchaseStatus = "pending" | "confirmed" | "rejected";
export type WithdrawalStatus = "pending" | "processed" | "rejected";

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          name: string;
          role: UserRole;
          bio: string | null;
          expertise: string | null;
          avatar_url: string | null;
          charter_signed_at: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          name: string;
          role?: UserRole;
          bio?: string | null;
          expertise?: string | null;
          avatar_url?: string | null;
          charter_signed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string;
          role?: UserRole;
          bio?: string | null;
          expertise?: string | null;
          avatar_url?: string | null;
          charter_signed_at?: string | null;
          created_at?: string;
        };
      };
      courses: {
        Row: {
          id: string;
          professor_id: string;
          title: string;
          description: string;
          language: CourseLanguage;
          level: CourseLevel;
          price: number;
          status: CourseStatus;
          pdf_url: string | null;
          objectives: string[];
          prerequisites: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          professor_id: string;
          title: string;
          description: string;
          language: CourseLanguage;
          level: CourseLevel;
          price: number;
          status?: CourseStatus;
          pdf_url?: string | null;
          objectives?: string[];
          prerequisites?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          professor_id?: string;
          title?: string;
          description?: string;
          language?: CourseLanguage;
          level?: CourseLevel;
          price?: number;
          status?: CourseStatus;
          pdf_url?: string | null;
          objectives?: string[];
          prerequisites?: string[];
          updated_at?: string;
        };
      };
      lessons: {
        Row: {
          id: string;
          course_id: string;
          axis_number: number;
          title: string;
          content: string | null;
          display_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          course_id: string;
          axis_number: number;
          title: string;
          content?: string | null;
          display_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          course_id?: string;
          axis_number?: number;
          title?: string;
          content?: string | null;
          display_order?: number;
        };
      };
      quizzes: {
        Row: {
          id: string;
          lesson_id: string;
          axis_number: number;
          questions: Json;
          passing_score: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          lesson_id: string;
          axis_number: number;
          questions: Json;
          passing_score?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          axis_number?: number;
          questions?: Json;
          passing_score?: number;
        };
      };
      purchases: {
        Row: {
          id: string;
          student_id: string;
          course_id: string;
          amount_paid: number;
          professor_commission: number;
          platform_commission: number;
          status: PurchaseStatus;
          purchased_at: string;
        };
        Insert: {
          id?: string;
          student_id: string;
          course_id: string;
          amount_paid: number;
          professor_commission: number;
          platform_commission: number;
          status?: PurchaseStatus;
          purchased_at?: string;
        };
        Update: {
          id?: string;
          student_id?: string;
          course_id?: string;
          amount_paid?: number;
          professor_commission?: number;
          platform_commission?: number;
          status?: PurchaseStatus;
          purchased_at?: string;
        };
      };
      progress: {
        Row: {
          id: string;
          student_id: string;
          course_id: string;
          current_axis: number;
          quiz_scores: Json;
          is_completed: boolean;
          last_accessed_at: string;
        };
        Insert: {
          id?: string;
          student_id: string;
          course_id: string;
          current_axis?: number;
          quiz_scores?: Json;
          is_completed?: boolean;
          last_accessed_at?: string;
        };
        Update: {
          id?: string;
          student_id?: string;
          course_id?: string;
          current_axis?: number;
          quiz_scores?: Json;
          is_completed?: boolean;
          last_accessed_at?: string;
        };
      };
      withdrawals: {
        Row: {
          id: string;
          professor_id: string;
          amount: number;
          status: WithdrawalStatus;
          requested_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          professor_id: string;
          amount: number;
          status?: WithdrawalStatus;
          requested_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          professor_id?: string;
          amount?: number;
          status?: WithdrawalStatus;
          requested_at?: string;
          processed_at?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: UserRole;
      course_status: CourseStatus;
      course_language: CourseLanguage;
      course_level: CourseLevel;
      purchase_status: PurchaseStatus;
      withdrawal_status: WithdrawalStatus;
    };
  };
}
